#!/usr/bin/env ruby
# encoding: utf-8
require "rubygems"
require "bundler/setup"

require ::File.expand_path('../lib/watcher', __FILE__)

::SMS.login('main@anlas.ru', 'QsZXVWS')

at_exit {
  ::SMS::logout
}

::Watcher.run
