#!/usr/bin/env ruby
# encoding: utf-8
require "rubygems"
require "bundler/setup"

require ::File.expand_path('../lib/watcher', __FILE__)

begin
  ::SMS.login('main@anlas.ru', 'QsZXVWS')
rescue ::SocketError
rescue => e
  puts "[SMS login error] #{e.message}"
end

at_exit {

  begin
    ::SMS::logout
  rescue ::SocketError
  rescue => e
    puts "[SMS logout error] #{e.message}"
  end

}

::Watcher.run
